### PR TITLE
fix branch used in gcloud actions

### PR DESCRIPTION
**Pull request by perpetuum7**

### CODE REVIEW

**Comment by perpetuum7** [comment]
Any updates?

**Comment by perpetuum7** [comment]
Bump

**Comment by perpetuum7** [comment]
Any updates?

**Comment by perpetuum7** [comment]
Bump

**Comment by perpetuum7** [comment]
Any updates?

**Comment by aaronisme** [comment]
@perpetuum7 thanks for the pr, I have fixed the build and release plan :)

**Pull request closed without merging**
